<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acerca' => '',
    'Aqui {cats, plural, =0{no hay gatos} =1{hay un gato} other{hay # gatos}}!' => '',
    'Bienvenido!' => '',
    'Contraseña' => '',
    'Desconectar' => '',
    'Español' => '',
    'Hola, {username}!' => '',
    'Hoy es {0, date, dd-M-yyyy}' => '',
    'Idioma' => '',
    'Ingles' => '',
    'Inglés' => '',
    'Ingresar' => '',
    'Iniciar sesión' => '',
    'Please fill out the following fields:' => 'Por favor complete los siguientes campos:',
    'Posts' => '',
    'Precio: {0, number, integer}' => '',
    'Precio: {0}' => '',
    'Precio: {0}, Conteo: {1}, Subtotal: {2}' => '',
    'Principal' => '',
    'Recuérdeme' => '',
    'Sistema de gestion de prestamos' => '',
    'Usuario' => '',
    'Usuarios' => '',
    'tu edad es {age}' => '',
    'usuario:' => '',
    'About' => '@@Acerca@@',
    'Congratulations!' => '@@Felicitaciones!@@',
    'Contact' => '@@Contacto@@',
    'English' => '@@Ingles@@',
    'Get started with Yii' => '@@Comience con Yii@@',
    'Hello, {username}!' => '@@Hola, {username}@@',
    'Here {cats, plural, =0{are no cats} =1{is a cat} other{there # cats}}!' => '@@Aqui {cats, plural, =0{no hay gatos} =1{hay un gato} other{hay # gatos}}!@@',
    'Home' => '@@Principal@@',
    'Login' => '@@Ingresar@@',
    'Logout' => '@@Desconectar@@',
    'Now is {0, date, dd-M-yyyy}' => '@@Ahora es {0, date, dd-M-yyyy}@@',
    'Password' => '@@Contraseña@@',
    'Please fill out the following fields:' => '@@Por favor complete los siguientes campos:@@',
    'Price: {0, number, integer}' => '@@Precio: {0, number, integer}@@',
    'Price: {0}' => '@@Precio: {0}@@',
    'Price: {0}, Count: {1}, Subtotal: {2}' => '@@Precio: {0}, Conteo: {1}, Subtotal: {2}@@',
    'Remember Me' => '@@Recuérdeme@@',
    'Spanish' => '@@Español@@',
    'Username' => '@@Usuario@@',
    'You have successfully created your Yii-powered application' => '@@Ha creado con éxito su aplicación con Yii.@@',
    'your age is {age}' => '@@tu edad es {age}@@',
    'Are you sure you want to delete this item?' => '¿Esta seguro de que quiere eliminar este artículo?',
    'Create' => 'Crear',
    'Create Post' => 'Crear Post',
    'Create Usuario' => 'Nuevo Usuario',
    'Delete' => 'Eliminar',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
];
