<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Español' => 'Spanish',
    'Inglés' => 'English',
    'Aqui {cats, plural, =0{no hay gatos} =1{hay un gato} other{hay # gatos}}!' => 'Here {cats, plural, =0{are no cats} =1{is a cat} other{there # cats}}!',
    'Are you sure you want to delete this item?' => '¿Esta seguro de que quiere eliminar este artículo?',
    'Create' => 'Crear',
    'Create Post' => 'Crear Post',
    'Delete' => 'Eliminar',
    'Hola, {username}!' => 'Hello, {username}',
    'Hoy es {0, date, dd-M-yyyy}' => 'Now is {0, date, dd-M-yyyy}',
    'Posts' => '',
    'Precio: {0, number, integer}' => 'Price {0, number, integer}',
    'Precio: {0}' => 'Price {0}',
    'Precio: {0}, Conteo: {1}, Subtotal: {2}' => 'Price: {0}, Count: {1}, Subtotal: {2}',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'tu edad es {age}' => 'your age is {age}',
    'Principal' => 'Home',
    'Acerca' => 'About',
    'Contacto' => 'Contact',
    'Idioma' => 'Language',
    'Sistema de Prestamos' => 'Loan System',
    'Bienvenido!' => 'Welcome!',
    'Sistema de gestion de prestamos' => 'Loan Management System',
    'Iniciar sesión' => 'Login',
    'usuario:' => 'user:',
    'Usuario' => 'User',
    'Contraseña' => 'Password',
    'Recuérdeme' => 'Remember Me',
    'Usuario y/o contraseña incorrecto.' => 'Incorrect username or password.',
    'Bienvenido!' => 'Welcome!',
];
